apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ai
  namespace: local-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeMode: Filesystem
  # selector:
  #   matchLabels:
  #     app: local-ai
  #   matchExpressions:
  #     - {key: type, operator: In, values: [local-ai]}

